services:
    wapinet_comment.helper:
        class: Wapinet\CommentBundle\Helper\Manager
        arguments: ["@doctrine"]

    fos_comment.manager.comment.default:
        class: Wapinet\CommentBundle\Entity\CommentManager
        arguments: ["@event_dispatcher", "@fos_comment.sorting_factory", "@fos_comment.entity_manager", "%fos_comment.model.comment.class%"]
        calls:
            - [setPaginate, ["@paginate"]]
            - [setRequestStack, ["@request_stack"]]

    wapinet_comment.twig_extension:
        class: Wapinet\CommentBundle\Twig\Extension\Comment
        arguments: ["@fos_comment.manager.comment"]
        tags:
            - {name: twig.extension, alias: wapinet_comment}

