services:
    wapinet_comment.helper:
        class: Wapinet\CommentBundle\Helper\Manager
        arguments: ["@doctrine"]

    wapinet_comment.manager.comment:
        class: Wapinet\CommentBundle\Entity\CommentManager
        arguments: ["@event_dispatcher"]
        calls:
            - [setPaginate, ["@paginate"]]
            - [setRequestStack, ["@request_stack"]]

    wapinet_comment.twig_extension:
        class: Wapinet\CommentBundle\Twig\Extension\Comment
        arguments: ["@wapinet_comment.manager.comment"]
        tags:
            - {name: twig.extension, alias: wapinet_comment}

