services:
    wapinet_uploader.type.file_url:
        class: WapinetUploaderBundle\Form\Type\FileUrlType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    wapinet_uploader.file_directory_namer:
        class: WapinetUploaderBundle\Naming\FileDirectoryNamer
        tags:
            - { name: file_directory_namer }
