Wapinet\Bundle\Entity\FileTags:
    type:  entity
    table: file_tags
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        file:
            targetEntity: Wapinet\Bundle\Entity\File
            cascade: ["persist"]
            inversedBy: fileTags
            joinColumn:
                name: file_id
                referencedColumnName: id
                nullable: false
    oneToOne:
        tag:
            targetEntity: Wapinet\Bundle\Entity\Tag
            cascade: ["persist", "remove"]
            joinColumn:
                name: tag_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false