Wapinet\Bundle\Entity\Online:
    type: entity
    table: online
    options:
        engine: MEMORY # не ставится связь с пользователями для типа MEMORY
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        datetime:
            type: datetime
        ip:
            type: string
            length: 255
        browser:
            type: string
            length: 255

    manyToOne:
        user:
            fetch: LAZY
            type: integer
            targetEntity: Wapinet\UserBundle\Entity\User
            joinColumns:
                user_id:
                    onDelete: CASCADE
                    onUpdate: CASCADE # не ставится автоматически. проставить вручную.
                    nullable: true

    uniqueConstraints:
        unique_idx:
            columns: ip, browser
