Wapinet\Bundle\Entity\Online:
    type: entity
    table: online
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        datetime:
            type: datetime
        ip:
            type: string
            length: 255
        browser:
            type: string
            length: 255
        request:
            type: object

    uniqueConstraints:
        unique_idx:
            columns: ip, browser
