Wapinet\Bundle\Entity\Sea:
    type: entity
    table: sea
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        datetime:
            type: datetime
        ip:
            type: string
            length: 255
        browser:
            type: string
            length: 255
        referer:
            type: string
            length: 255
            nullable: true