services:
    wapinet.type.tags:
        class: WapinetBundle\Form\Type\TagsType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    pagerfanta.view.default:
        class: WapinetBundle\Pagerfanta\View
        public: false
        tags: [{ name: pagerfanta.view, alias: default }]

#    wapinet.bbcode.twig_extension:
#        class: WapinetBundle\Twig\Extension\Bbcode
#        arguments: ["@router.request_context"]
#        tags:
#            - {name: twig.extension, alias: wapinet_bbcode}

#    wapinet.date.twig_extension:
#        class: WapinetBundle\Twig\Extension\Date
#        arguments: ["@timezone"]
#        tags:
#            - {name: twig.extension, alias: wapinet_date}

#    wapinet.size.twig_extension:
#        class: WapinetBundle\Twig\Extension\Size
#        tags:
#            - {name: twig.extension, alias: wapinet_size}

#    wapinet.count.twig_extension:
#        class: WapinetBundle\Twig\Extension\Count
#        tags:
#            - {name: twig.extension, alias: wapinet_count}

#    wapinet.geoip2.twig_extension:
#        class: WapinetBundle\Twig\Extension\Geoip2
#        arguments: ["@geoip2"]
#        tags:
#            - {name: twig.extension, alias: wapinet_geoip2}

#    wapinet.video.twig_extension:
#        class: WapinetBundle\Twig\Extension\Video
#        arguments: ["@service_container"]
#        tags:
#            - {name: twig.extension, alias: wapinet_video}

#    wapinet.audio.twig_extension:
#        class: WapinetBundle\Twig\Extension\Audio
#        arguments: ["@service_container"]
#        tags:
#            - {name: twig.extension, alias: wapinet_audio}

#    wapinet.java_app.twig_extension:
#        class: WapinetBundle\Twig\Extension\JavaApp
#        arguments: ["@service_container"]
#        tags:
#            - {name: twig.extension, alias: wapinet_java_app}

#    wapinet.android_app.twig_extension:
#        class: WapinetBundle\Twig\Extension\AndroidApp
#        arguments: ["@service_container"]
#        tags:
#            - {name: twig.extension, alias: wapinet_android_app}

#    wapinet.archive.twig_extension:
#        class: WapinetBundle\Twig\Extension\Archive
#        arguments: ["@service_container"]
#        tags:
#            - {name: twig.extension, alias: wapinet_archive}

#    wapinet.torrent.twig_extension:
#        class: WapinetBundle\Twig\Extension\Torrent
#        arguments: ["@service_container"]
#        tags:
#            - {name: twig.extension, alias: wapinet_torrent}

#    wapinet.playlist.twig_extension:
#        class: WapinetBundle\Twig\Extension\Playlist
#        arguments: ["@service_container"]
#        tags:
#            - {name: twig.extension, alias: wapinet_playlist}

#    wapinet.online.twig_extension:
#        class: WapinetBundle\Twig\Extension\Online
#        arguments: ["@doctrine.orm.entity_manager"]
#        tags:
#            - {name: twig.extension, alias: wapinet_online}

#    wapinet.breadcrumbs.twig_extension:
#        class: WapinetBundle\Twig\Extension\Breadcrumbs
#        arguments: ["@service_container"]
#        tags:
#            - {name: twig.extension, alias: wapinet_breadcrumbs}

#    wapinet.panel.twig_extension:
#        class: WapinetBundle\Twig\Extension\Panel
#        arguments: ["@service_container"]
#        tags:
#            - {name: twig.extension, alias: wapinet_panel}

#    wapinet.file.twig_extension:
#        class: WapinetBundle\Twig\Extension\File
#        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
#        tags:
#            - {name: twig.extension, alias: wapinet_file}

#    wapinet.guestbook.twig_extension:
#        class: WapinetBundle\Twig\Extension\Guestbook
#        arguments: ["@doctrine.orm.entity_manager"]
#        tags:
#            - {name: twig.extension, alias: wapinet_guestbook}

#    wapinet.gist.twig_extension:
#        class: WapinetBundle\Twig\Extension\Gist
#        arguments: ["@doctrine.orm.entity_manager"]
#        tags:
#            - {name: twig.extension, alias: wapinet_gist}

#    wapinet.base64.twig_extension:
#        class: WapinetBundle\Twig\Extension\Base64
#        tags:
#            - {name: twig.extension, alias: base64}

#    wapinet.forum.twig_extension:
#        class: WapinetBundle\Twig\Extension\Forum
#        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
#        tags:
#            - {name: twig.extension, alias: wapinet_forum}

    online.listener:
        class: WapinetBundle\EventListener\OnlineListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    error:
        class: WapinetBundle\Helper\Error

    mime:
        class: WapinetBundle\Helper\Mime
        arguments: ["@service_container"]

    timezone:
        public: true
        class: WapinetBundle\Helper\Timezone
        arguments: ["@security.token_storage"]

    file:
        class: WapinetBundle\Helper\File\File
        arguments: ["@service_container"]

    file_meta:
        class: WapinetBundle\Helper\File\Meta
        arguments: ["@service_container"]

    curl:
        public: true
        class: WapinetBundle\Helper\Curl
        arguments: ["@service_container"]

    ffmpeg:
        class: WapinetBundle\Helper\Ffmpeg
        arguments: ["@service_container"]

    translit:
        class: WapinetBundle\Helper\Translit

    paginate:
        public: true
        class: WapinetBundle\Helper\Paginate
        arguments: ["@service_container"]

    getid3:
        class: WapinetBundle\Helper\Getid3

    geoip2:
        class: WapinetBundle\Helper\Geoip2
        arguments: ["@service_container"]

    bot_checker:
        class: WapinetBundle\Helper\BotChecker

    stop_spam:
        class: WapinetBundle\Helper\StopSpam

    hash:
        class: WapinetBundle\Helper\Hash

    code:
        class: WapinetBundle\Helper\Code

    phpwhois:
        class: WapinetBundle\Helper\Phpwhois

    css_validator:
        class: WapinetBundle\Helper\CssValidator

    html_validator:
        class: WapinetBundle\Helper\HtmlValidator

    php_validator:
        public: true
        class: WapinetBundle\Helper\PhpValidator
        arguments: ["@service_container"]

    apk:
        class: WapinetBundle\Helper\Apk

    rates:
        class: WapinetBundle\Helper\Rates
        arguments: ["@service_container"]

    horoscope:
        class: WapinetBundle\Helper\Horoscope
        arguments: ["@service_container"]

    mass_media:
        class: WapinetBundle\Helper\MassMedia
        arguments: ["@service_container"]

    bash:
        public: true
        class: WapinetBundle\Helper\Bash
        arguments: ["@service_container"]

    sphinx:
        class: WapinetBundle\Helper\Sphinx
        arguments: ["@service_container"]

    archive_zip:
        public: true
        class: WapinetBundle\Helper\Archiver\ArchiveZip
        arguments: ["@service_container"]

    archive_rar:
        class: WapinetBundle\Helper\Archiver\ArchiveRar
        arguments: ["@service_container"]

    archive_7z:
        public: true
        class: WapinetBundle\Helper\Archiver\Archive7z
        arguments: ["@service_container"]

    torrent:
        class: WapinetBundle\Helper\Torrent
        arguments: ["@service_container"]

    playlist:
        class: WapinetBundle\Helper\Playlist
        arguments: ["@service_container"]

#    wapinet.twig_extension:
#        class: WapinetBundle\Twig\Extension\News
#        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
#        tags:
#            - {name: twig.extension, alias: news}

    wapinet.form.file.upload:
        class: WapinetBundle\Form\Type\File\UploadType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    wapinet.form.email.email:
        class: WapinetBundle\Form\Type\Email\EmailType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    wapinet.form.guestbook.message:
        class: WapinetBundle\Form\Type\Guestbook\MessageType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    wapinet.form.code.code:
        class: WapinetBundle\Form\Type\Code\CodeType
        arguments: ["@code"]
        tags:
            - { name: form.type }

    wapinet.form.hash.hash:
        class: WapinetBundle\Form\Type\Hash\HashType
        arguments: ["@hash"]
        tags:
            - { name: form.type }

    wapinet.file_voter:
        class: WapinetBundle\Security\FileVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    wapinet.gist_voter:
        class: WapinetBundle\Security\GistVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    wapinet.file_uploader.namer_file_directory:
        class: WapinetBundle\Uploader\Naming\FileDirectoryNamer
        public: true

    wapinet.user.profile.form.type:
        class: WapinetBundle\Form\Type\User\ProfileType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type }

    wapinet.user.event.message:
        class: WapinetBundle\EventListener\EventMessage
        arguments: ["@fos_message.message_manager", "@doctrine.orm.entity_manager", "@router"]
        tags:
            - { name: kernel.event_subscriber }

    wapinet.user.listener.last_activity:
            class: WapinetBundle\EventListener\ListenerLastActivity
            arguments: ["@service_container", "@doctrine.orm.entity_manager"]
            tags:
                - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    wapinet.user.event.friends:
        class: WapinetBundle\EventListener\EventFriends
        arguments: ["@doctrine.orm.entity_manager", "@router"]
        tags:
            - { name: kernel.event_subscriber }
