services:
    wapinet.type.tags:
        class: WapinetBundle\Form\Type\TagsType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    pagerfanta.view.default:
        class: WapinetBundle\Pagerfanta\View
        tags: [{ name: pagerfanta.view, alias: default }]

    online.listener:
        class: WapinetBundle\EventListener\OnlineListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    file:
        class: WapinetBundle\Helper\File\File
        arguments: ["@service_container"]
        public: true

    file_meta:
        class: WapinetBundle\Helper\File\Meta
        arguments: ["@service_container"]
        public: true

    curl:
        class: WapinetBundle\Helper\Curl
        arguments: ["@service_container"]
        public: true

    ffmpeg:
        class: WapinetBundle\Helper\Ffmpeg
        arguments: ["@service_container"]
        public: true

    translit:
        class: WapinetBundle\Helper\Translit
        public: true

    paginate:
        class: WapinetBundle\Helper\Paginate
        arguments: ["@service_container"]
        public: true

    getid3:
        class: WapinetBundle\Helper\Getid3
        public: true

    bot_checker:
        class: WapinetBundle\Helper\BotChecker
        public: true

    stop_spam:
        class: WapinetBundle\Helper\StopSpam
        public: true

    hash:
        class: WapinetBundle\Helper\Hash
        public: true

    code:
        class: WapinetBundle\Helper\Code
        public: true

    phpwhois:
        class: WapinetBundle\Helper\Phpwhois
        public: true

    css_validator:
        class: WapinetBundle\Helper\CssValidator
        public: true

    html_validator:
        class: WapinetBundle\Helper\HtmlValidator
        public: true

    php_validator:
        class: WapinetBundle\Helper\PhpValidator
        arguments: ["@service_container"]
        public: true

    apk:
        class: WapinetBundle\Helper\Apk
        public: true

    sphinx:
        class: WapinetBundle\Helper\Sphinx
        arguments: ["@service_container"]
        public: true

    archive_zip:
        class: WapinetBundle\Helper\Archiver\ArchiveZip
        arguments: ["@service_container"]
        public: true

    archive_rar:
        class: WapinetBundle\Helper\Archiver\ArchiveRar
        arguments: ["@service_container"]
        public: true

    archive_7z:
        class: WapinetBundle\Helper\Archiver\Archive7z
        arguments: ["@service_container"]
        public: true

    torrent:
        class: WapinetBundle\Helper\Torrent
        arguments: ["@service_container"]
        public: true

    playlist:
        class: WapinetBundle\Helper\Playlist
        arguments: ["@service_container"]
        public: true

    wapinet.form.file.upload:
        class: WapinetBundle\Form\Type\File\UploadType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    wapinet.form.email.email:
        class: WapinetBundle\Form\Type\Email\EmailType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    wapinet.form.guestbook.message:
        class: WapinetBundle\Form\Type\Guestbook\MessageType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    wapinet.form.code.code:
        class: WapinetBundle\Form\Type\Code\CodeType
        arguments: ["@code"]
        tags:
            - { name: form.type }

    wapinet.form.hash.hash:
        class: WapinetBundle\Form\Type\Hash\HashType
        arguments: ["@hash"]
        tags:
            - { name: form.type }

    wapinet.file_voter:
        class: WapinetBundle\Security\FileVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    wapinet.gist_voter:
        class: WapinetBundle\Security\GistVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    wapinet.file_uploader.namer_file_directory:
        class: WapinetBundle\Uploader\Naming\FileDirectoryNamer
        public: true

    wapinet.user.profile.form.type:
        class: WapinetBundle\Form\Type\User\ProfileType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type }

    wapinet.user.listener.last_activity:
        class: WapinetBundle\EventListener\ListenerLastActivity
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    wapinet.user.event.friends:
        class: WapinetBundle\EventListener\EventFriends
        arguments: ["@doctrine.orm.entity_manager", "@router"]
        tags:
            - { name: kernel.event_subscriber }
