#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

easy_admin:
    design:
        menu:
            - { label: 'Мониторинг', route: 'monitoring', default: true }
            - Files
            - Tags
            - News
            - Users
            - Subscribers
            - Panel
            - Gists
            - Guestbook
        assets:
            css:
                - 'build/app.css'
    site_name: '%wapinet_title%'
    entities:
        Files:
            disabled_actions: ['new']
            label: 'Файлы'
            class: App\Entity\File
            list:
                filters: ['originalFileName', 'user', 'hidden']
                fields:
                    - { property: 'originalFileName', label: 'Имя файла' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'user', label: 'Пользователь' }
                    - { property: 'mimeType', label: 'MIME тип' }
                    - { property: 'fileSize', label: 'Размер' }
                    - { property: 'description', label: 'Описание' }
                    - { property: 'countViews', label: 'Просмотров' }
                    - { property: 'password', label: 'Пароль', type: 'boolean' }
                    - { property: 'hidden', label: 'Скрыт' }
            form:
                fields:
                    - { property: 'originalFileName', label: 'Имя файла' }
                    - { property: 'mimeType', label: 'MIME тип' }
                    - { property: 'description', label: 'Описание', type: 'textarea' }
                    #- { property: 'meta', label: 'Данные', type_options: { read_only: true, required: false } }
                    - { property: 'countViews', label: 'Просмотров' }
                    - { property: 'hidden', label: 'Скрыт', type_options: {required: false} }
        Tags:
            disabled_actions: ['new']
            label: 'Тэги'
            class: App\Entity\Tag
            list:
                fields:
                    - { property: 'name', label: 'Имя' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'count', label: 'Использовано раз' }
            form:
                fields:
                    - { property: 'name', label: 'Имя' }
                    - { property: 'count', label: 'Использовано раз' }
        News:
            label: 'Новости'
            class: App\Entity\News
            list:
                fields:
                    - { property: 'subject', label: 'Заголовок' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'updatedAt', label: 'Дата обновления' }
            form:
                fields:
                    - { property: 'subject', label: 'Заголовок' }
                    - { property: 'body', label: 'Содержание' }
        Users:
            disabled_actions: ['new']
            label: 'Пользователи'
            class: App\Entity\User
            list:
                fields:
                    - { property: 'username', label: 'Логин' }
                    - { property: 'emailCanonical', label: 'Аватар', type: 'image', template: 'avatar.html.twig' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'roles', label: 'Роли' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'lastActivity', label: 'Дата последней активности' }
            form:
                fields:
                    - { property: 'username', label: 'Логин' }
                    - { property: 'enabled', label: 'Активен', type_options: {required: false} }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'roles', label: 'Роли', type: 'choice', type_options: { expanded: true, multiple: true, choices: {'Админ': 'ROLE_SUPER_ADMIN', 'Модератор': 'ROLE_ADMIN', 'Пользователь': 'ROLE_USER'} } }
                    - { property: 'sex', label: 'Пол', type: 'choice', type_options: {choices: {'Мужской': 'm', 'Женский': 'f'}, required: false} }
                    - { property: 'birthday', label: 'День рождения', type: 'birthday', type_options: {required: false} }
                    - { property: 'timezone', label: 'Временная зона', type: 'timezone', type_options: {required: false} }
                    - { property: 'info', label: 'Дополнительная информация', type: 'textarea', type_options: {required: false} }
        Subscribers:
            disabled_actions: ['new']
            label: 'Подписки'
            class: App\Entity\Subscriber
            list:
                fields:
                    - { property: 'user', label: 'Пользователь' }
                    - { property: 'emailNews', label: 'Новости' }
                    - { property: 'emailFriends', label: 'События друзей' }
            form:
                fields:
                    - { property: 'emailNews', label: 'Новости' }
                    - { property: 'emailFriends', label: 'События друзей' }
        Panel:
            disabled_actions: ['new']
            label: 'Панель'
            class: App\Entity\Panel
            list:
                fields:
                    - { property: 'user', label: 'Пользователь' }
                    - { property: 'forum', label: 'Форум'}
                    - { property: 'guestbook', label: 'Гостевая' }
                    - { property: 'gist', label: 'Блоги' }
                    - { property: 'file', label: 'Файлообменник' }
                    - { property: 'archiver', label: 'Архиватор' }
                    - { property: 'downloads', label: 'Развлечения' }
                    - { property: 'utilities', label: 'Утилиты' }
                    - { property: 'programming', label: 'WEB мастерская' }
            form:
                fields:
                    - { property: 'forum', label: 'Форум'}
                    - { property: 'guestbook', label: 'Гостевая' }
                    - { property: 'gist', label: 'Блоги' }
                    - { property: 'file', label: 'Файлообменник' }
                    - { property: 'archiver', label: 'Архиватор' }
                    - { property: 'downloads', label: 'Развлечения' }
                    - { property: 'utilities', label: 'Утилиты' }
                    - { property: 'programming', label: 'WEB мастерская' }
        Gists:
            disabled_actions: ['new']
            label: 'Блоги'
            class: App\Entity\Gist
            list:
                fields:
                    - { property: 'user', label: 'Пользователь' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'subject', label: 'Тема' }
            form:
                fields:
                    - { property: 'subject', label: 'Тема' }
                    - { property: 'body', label: 'Сообщение' }
        Guestbook:
            disabled_actions: ['new']
            label: 'Гостевая'
            class: App\Entity\Guestbook
            list:
                fields:
                    - { property: 'user', label: 'Пользователь' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'message', label: 'Сообщение' }
            form:
                fields:
                    - { property: 'message', label: 'Сообщение', type: 'textarea' }
