archiver_index:
    path: /
    defaults: { _controller: App\Controller\ArchiverController::indexAction }

archiver_create:
    path: /create
    defaults: { _controller: App\Controller\ArchiverController::createAction }

archiver_extract:
    path: /extract
    defaults: { _controller: App\Controller\ArchiverController::extractAction }

archiver_edit:
    path: /edit/{archive}
    defaults: { _controller: App\Controller\ArchiverController::editAction }
    requirements:
        archive: "archive[a-z0-9]+"

archiver_delete_file:
    path: /delete/{archive}/{name}
    defaults: { _controller: App\Controller\ArchiverController::deleteFileAction }
    methods: [POST]
    requirements:
        archive: "archive[a-z0-9]+"
    options:
        expose: true

archiver_download_file:
    path: /download/{archive}/{name}
    defaults: { _controller: App\Controller\ArchiverController::downloadFileAction }
    requirements:
        archive: "archive[a-z0-9]+"

archiver_download:
    path: /download/{archive}.zip
    defaults: { _controller: App\Controller\ArchiverController::downloadAction }
    requirements:
        archive: "archive[a-z0-9]+"

