audio_tags_index:
    path: /
    defaults: { _controller: App\Controller\AudioTagsController::indexAction }

audio_tags_edit:
    path: /edit/{fileName}/{originalFileName}
    defaults: { _controller: App\Controller\AudioTagsController::editAction }

audio_tags_download:
    path: /download/{fileName}/{originalFileName}
    defaults: { _controller: App\Controller\AudioTagsController::downloadAction }
