vk_api_get:
    path: /get/{method}
    controller: App\Controller\VkApiController::getAction
    defaults:
        _format: json
    methods: [POST]
    requirements:
        method: '.+'
    options:
        expose: true
