index:
    pattern:  /
    defaults: { _controller: WapinetBundle:Default:index }

about:
    pattern:  /about
    defaults: { _controller: WapinetBundle:Default:about }

utilities:
    pattern:  /utilities
    defaults: { _controller: WapinetBundle:Default:utilities }

downloads:
    pattern:  /downloads
    defaults: { _controller: WapinetBundle:Default:downloads }

programming:
    pattern:  /programming
    defaults: { _controller: WapinetBundle:Default:programming }

open_source:
    pattern:  /open_source
    defaults: { _controller: WapinetBundle:Default:openSource }

gmanager:
    pattern:  /gmanager
    defaults: { _controller: WapinetBundle:Default:gmanager }

buy_php_scripts:
    pattern:  /buy_php_scripts
    defaults: { _controller: WapinetBundle:Default:buyPhpScripts }

browser_info:
    pattern: /browser_info
    defaults: { _controller: WapinetBundle:BrowserInfo:index }

mobile_code:
    resource: "@WapinetBundle/Resources/config/routing/mobile_code.yml"
    prefix:   /mobile_code

icq:
    resource: "@WapinetBundle/Resources/config/routing/icq.yml"
    prefix:   /icq

email:
    resource: "@WapinetBundle/Resources/config/routing/email.yml"
    prefix:   /email

translate:
    resource: "@WapinetBundle/Resources/config/routing/translate.yml"
    prefix:   /translate

pagerank:
    resource: "@WapinetBundle/Resources/config/routing/pagerank.yml"
    prefix:   /pagerank

unicode:
    resource: "@WapinetBundle/Resources/config/routing/unicode.yml"
    prefix:   /unicode

rename:
    resource: "@WapinetBundle/Resources/config/routing/rename.yml"
    prefix:   /rename

sms:
    resource: "@WapinetBundle/Resources/config/routing/sms.yml"
    prefix:   /sms

audio_tags:
    resource: "@WapinetBundle/Resources/config/routing/audio_tags.yml"
    prefix:   /audio_tags
