index:
    path:  /
    defaults: { _controller: WapinetBundle:Default:index }

about:
    path:  /about
    defaults: { _controller: WapinetBundle:Default:about }

log:
    path:  /log
    defaults: { _controller: WapinetBundle:Default:log }

online:
    path:  /online
    defaults: { _controller: WapinetBundle:Default:online }

utilities:
    path:  /utilities
    defaults: { _controller: WapinetBundle:Default:utilities }

downloads:
    path:  /downloads
    defaults: { _controller: WapinetBundle:Default:downloads }

programming:
    path:  /programming
    defaults: { _controller: WapinetBundle:Default:programming }

open_source:
    path:  /open_source
    defaults: { _controller: WapinetBundle:Default:openSource }

gmanager:
    path:  /gmanager
    defaults: { _controller: WapinetBundle:Default:gmanager }

buy_php_scripts:
    path:  /buy_php_scripts
    defaults: { _controller: WapinetBundle:Default:buyPhpScripts }

textbook:
    path:  /textbook
    defaults: { _controller: WapinetBundle:Default:textbook }


# Проверка синтаксиса для Gmanager
syntax:
    path:  /syntax
    defaults: { _controller: WapinetBundle:Syntax:index }
syntax_old:
    path:  /syntax2/index.php
    defaults: { _controller: WapinetBundle:Syntax:index }


browser_info:
    path: /browser_info
    defaults: { _controller: WapinetBundle:BrowserInfo:index }

mobile_code:
    resource: "@WapinetBundle/Resources/config/routing/mobile_code.yml"
    prefix:   /mobile_code

icq:
    resource: "@WapinetBundle/Resources/config/routing/icq.yml"
    prefix:   /icq

hash:
    resource: "@WapinetBundle/Resources/config/routing/hash.yml"
    prefix:   /hash

code:
    resource: "@WapinetBundle/Resources/config/routing/code.yml"
    prefix:   /code

email:
    resource: "@WapinetBundle/Resources/config/routing/email.yml"
    prefix:   /email

translate:
    resource: "@WapinetBundle/Resources/config/routing/translate.yml"
    prefix:   /translate

pagerank:
    resource: "@WapinetBundle/Resources/config/routing/pagerank.yml"
    prefix:   /pagerank

unicode:
    resource: "@WapinetBundle/Resources/config/routing/unicode.yml"
    prefix:   /unicode

rename:
    resource: "@WapinetBundle/Resources/config/routing/rename.yml"
    prefix:   /rename

sms:
    resource: "@WapinetBundle/Resources/config/routing/sms.yml"
    prefix:   /sms

audio_tags:
    resource: "@WapinetBundle/Resources/config/routing/audio_tags.yml"
    prefix:   /audio_tags

whois:
    resource: "@WapinetBundle/Resources/config/routing/whois.yml"
    prefix:   /whois

php_obfuscator:
    resource: "@WapinetBundle/Resources/config/routing/php_obfuscator.yml"
    prefix:   /php_obfuscator

rest:
    resource: "@WapinetBundle/Resources/config/routing/rest.yml"
    prefix:   /rest

css_validator:
    resource: "@WapinetBundle/Resources/config/routing/css_validator.yml"
    prefix:   /css_validator

html_validator:
    resource: "@WapinetBundle/Resources/config/routing/html_validator.yml"
    prefix:   /html_validator

php_validator:
    resource: "@WapinetBundle/Resources/config/routing/php_validator.yml"
    prefix:   /php_validator

weather:
    resource: "@WapinetBundle/Resources/config/routing/weather.yml"
    prefix:   /weather

rates:
    resource: "@WapinetBundle/Resources/config/routing/rates.yml"
    prefix:   /rates

horoscope:
    resource: "@WapinetBundle/Resources/config/routing/horoscope.yml"
    prefix:   /horoscope

mass_media:
    resource: "@WapinetBundle/Resources/config/routing/mass_media.yml"
    prefix:   /mass_media

bash:
    resource: "@WapinetBundle/Resources/config/routing/bash.yml"
    prefix:   /bash

siza:
    resource: "@WapinetBundle/Resources/config/routing/siza.yml"
    prefix:   /siza

archiver:
    resource: "@WapinetBundle/Resources/config/routing/archiver.yml"
    prefix:   /archiver

file:
    resource: "@WapinetBundle/Resources/config/routing/file.yml"
    prefix:   /file

news:
    resource: "@WapinetBundle/Resources/config/routing/news.yml"
    prefix:   /news

guestbook:
    resource: "@WapinetBundle/Resources/config/routing/guestbook.yml"
    prefix:   /guestbook

gist:
    resource: "@WapinetBundle/Resources/config/routing/gist.yml"
    prefix:   /gist

proxy_index:
    path: /proxy/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: %wapinet_proxy_url%
        permanent: true

forum_index:
    path: /forum/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: %wapinet_forum_url%
        permanent: true

sea_index:
    path: /sea/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: %wapinet_sea_url%
        permanent: true

sea_readme:
    path: /sea/readme
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: %wapinet_sea_url%/readme.txt
        permanent: true

sea_changelog:
    path: /sea/changelog
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: %wapinet_sea_url%/changelog.txt
        permanent: true
