index:
    pattern:  /
    defaults: { _controller: WapinetBundle:Default:index }

about:
    pattern:  /about
    defaults: { _controller: WapinetBundle:Default:about }

utilities:
    pattern:  /utilities
    defaults: { _controller: WapinetBundle:Default:utilities }

downloads:
    pattern:  /downloads
    defaults: { _controller: WapinetBundle:Default:downloads }

programming:
    pattern:  /programming
    defaults: { _controller: WapinetBundle:Default:programming }

source_code:
    pattern:  /source_code
    defaults: { _controller: WapinetBundle:Default:sourceCode }

gmanager:
    pattern:  /gmanager
    defaults: { _controller: WapinetBundle:Default:gmanager }

buy_php_scripts:
    pattern:  /buy_php_scripts
    defaults: { _controller: WapinetBundle:Default:buyPhpScripts }

browser_info:
    pattern: /browser_info
    defaults: { _controller: WapinetBundle:BrowserInfo:index }

mobile_code:
    resource: "@WapinetBundle/Resources/config/routing/mobile_code.yml"
    prefix:   /mobile_code
