services:
    wapinet.type.tags:
        class: Wapinet\Bundle\Form\Type\TagsType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: tags }

    pagerfanta.view.default:
        class: Wapinet\Bundle\Pagerfanta\View
        public: false
        tags: [{ name: pagerfanta.view, alias: default }]

    wapinet.bbcode.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Bbcode
        arguments: ["@router.request_context"]
        tags:
            - {name: twig.extension, alias: wapinet_bbcode}

    wapinet.date.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Date
        arguments: ["@timezone"]
        tags:
            - {name: twig.extension, alias: wapinet_date}

    wapinet.size.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Size
        tags:
            - {name: twig.extension, alias: wapinet_size}

    wapinet.count.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Count
        tags:
            - {name: twig.extension, alias: wapinet_count}

    wapinet.geoip2.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Geoip2
        arguments: ["@geoip2"]
        tags:
            - {name: twig.extension, alias: wapinet_geoip2}

    wapinet.video.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Video
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension, alias: wapinet_video}

    wapinet.audio.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Audio
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension, alias: wapinet_audio}

    wapinet.java_app.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\JavaApp
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension, alias: wapinet_java_app}

    wapinet.android_app.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\AndroidApp
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension, alias: wapinet_android_app}

    wapinet.archive.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Archive
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension, alias: wapinet_archive}

    wapinet.torrent.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Torrent
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension, alias: wapinet_torrent}

    wapinet.playlist.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Playlist
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension, alias: wapinet_playlist}

    wapinet.online.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Online
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - {name: twig.extension, alias: wapinet_online}

    wapinet.breadcrumbs.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Breadcrumbs
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension, alias: wapinet_breadcrumbs}

    wapinet.panel.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Panel
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension, alias: wapinet_panel}

    wapinet.file.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\File
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
        tags:
            - {name: twig.extension, alias: wapinet_file}

    wapinet.guestbook.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Guestbook
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - {name: twig.extension, alias: wapinet_guestbook}

    wapinet.gist.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Gist
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - {name: twig.extension, alias: wapinet_gist}

    base64.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Base64
        tags:
            - {name: twig.extension, alias: base64}

    wapinet.forum.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Forum
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
        tags:
            - {name: twig.extension, alias: wapinet_forum}

    online.listener:
        class: Wapinet\Bundle\EventListener\OnlineListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    error:
        class: Wapinet\Bundle\Helper\Error

    mime:
        class: Wapinet\Bundle\Helper\Mime
        arguments: ["@service_container"]

    timezone:
        class: Wapinet\Bundle\Helper\Timezone
        arguments: ["@security.token_storage"]

    file:
        class: Wapinet\Bundle\Helper\File\File
        arguments: ["@service_container"]

    file_meta:
        class: Wapinet\Bundle\Helper\File\Meta
        arguments: ["@service_container"]

    curl:
        class: Wapinet\Bundle\Helper\Curl
        arguments: ["@service_container"]

    translit:
        class: Wapinet\Bundle\Helper\Translit

    paginate:
        class: Wapinet\Bundle\Helper\Paginate
        arguments: ["@service_container"]

    getid3:
        class: Wapinet\Bundle\Helper\Getid3

    geoip2:
        class: Wapinet\Bundle\Helper\Geoip2
        arguments: ["@service_container"]

    bot_checker:
        class: Wapinet\Bundle\Helper\BotChecker

    hash:
        class: Wapinet\Bundle\Helper\Hash

    code:
        class: Wapinet\Bundle\Helper\Code

    phpwhois:
        class: Wapinet\Bundle\Helper\Phpwhois

    css_validator:
        class: Wapinet\Bundle\Helper\CssValidator

    html_validator:
        class: Wapinet\Bundle\Helper\HtmlValidator

    php_validator:
        class: Wapinet\Bundle\Helper\PhpValidator
        arguments: ["@service_container"]

    apk:
        class: Wapinet\Bundle\Helper\Apk

    weather:
        class: Wapinet\Bundle\Helper\Weather
        arguments: ["@service_container"]

    rates:
        class: Wapinet\Bundle\Helper\Rates
        arguments: ["@service_container"]

    horoscope:
        class: Wapinet\Bundle\Helper\Horoscope
        arguments: ["@service_container"]

    mass_media:
        class: Wapinet\Bundle\Helper\MassMedia
        arguments: ["@service_container"]

    bash:
        class: Wapinet\Bundle\Helper\Bash
        arguments: ["@service_container"]

    siza:
        class: Wapinet\Bundle\Helper\Siza
        arguments: ["@service_container"]

    sphinx:
        class: Wapinet\Bundle\Helper\Sphinx
        arguments: ["@service_container"]
        scope: prototype

    archive_zip:
        class: Wapinet\Bundle\Helper\Archiver\ArchiveZip
        arguments: ["@service_container"]

    archive_rar:
        class: Wapinet\Bundle\Helper\Archiver\ArchiveRar
        arguments: ["@service_container"]

    archive_7z:
        class: Wapinet\Bundle\Helper\Archiver\Archive7z
        arguments: ["@service_container"]

    torrent:
        class: Wapinet\Bundle\Helper\Torrent
        arguments: ["@service_container"]

    playlist:
        class: Wapinet\Bundle\Helper\Playlist
        arguments: ["@service_container"]

    wapinet.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\News
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
        tags:
            - {name: twig.extension, alias: news}

    wapinet.event.easy_admin:
        class: Wapinet\Bundle\EventListener\EasyAdminSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    wapinet.form.file.upload:
        class: Wapinet\Bundle\Form\Type\File\UploadType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    wapinet.form.email.email:
        class: Wapinet\Bundle\Form\Type\Email\EmailType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    wapinet.form.sms.sms:
        class: Wapinet\Bundle\Form\Type\Sms\SmsType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    wapinet.form.code.code:
        class: Wapinet\Bundle\Form\Type\Code\CodeType
        arguments: ["@code"]
        tags:
            - { name: form.type }

    wapinet.form.hash.hash:
        class: Wapinet\Bundle\Form\Type\Hash\HashType
        arguments: ["@hash"]
        tags:
            - { name: form.type }