services:
    wapinet.date.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Date
        tags:
            - {name: twig.extension, alias: wapinet_date}

    wapinet.online.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Online
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: twig.extension, alias: wapinet_online}

    wapinet.menu.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Menu
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_menu}

    curl:
        class: Wapinet\Bundle\Helper\Curl
        arguments: [@service_container]

    paginate:
        class: Wapinet\Bundle\Helper\Paginate
        arguments: [@service_container]

    getid3:
        class: Wapinet\Bundle\Helper\Getid3

    wapinet.type.file_url:
        class: Wapinet\Bundle\Form\Type\FileUrlType
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: file_url }
