services:
    pagerfanta.view.default:
        class: Wapinet\Bundle\Pagerfanta\View
        public: false
        tags: [{ name: pagerfanta.view, alias: default }]

    wapinet.date.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Date
        tags:
            - {name: twig.extension, alias: wapinet_date}

    wapinet.size.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Size
        tags:
            - {name: twig.extension, alias: wapinet_size}

    wapinet.video.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Video
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_video}

    wapinet.image.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Image
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_image}

    wapinet.audio.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Audio
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_audio}

    wapinet.archive.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Archive
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_archive}

    wapinet.online.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Online
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: wapinet_online}

    wapinet.breadcrumbs.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Breadcrumbs
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_breadcrumbs}

    wapinet.panel.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Panel
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_panel}

    wapinet.file.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\File
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: wapinet_file}

    base64.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Base64
        tags:
            - {name: twig.extension, alias: base64}

    wapinet.forum.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Forum
        arguments: [@service_container, @doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: wapinet_forum}

    online.listener:
        class: Wapinet\Bundle\Listener\OnlineListener
        arguments: [@service_container, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    error:
        class: Wapinet\Bundle\Helper\Error
    mime:
        class: Wapinet\Bundle\Helper\Mime
        arguments: [@service_container]
    file:
        class: Wapinet\Bundle\Helper\File
        arguments: [@service_container]
    curl:
        class: Wapinet\Bundle\Helper\Curl
        arguments: [@service_container]

    paginate:
        class: Wapinet\Bundle\Helper\Paginate
        arguments: [@service_container]

    getid3:
        class: Wapinet\Bundle\Helper\Getid3

    phpwhois:
        class: Wapinet\Bundle\Helper\Phpwhois

    css_validator:
        class: Wapinet\Bundle\Helper\CssValidator

    html_validator:
        class: Wapinet\Bundle\Helper\HtmlValidator

    php_validator:
        class: Wapinet\Bundle\Helper\PhpValidator
        arguments: [@service_container]

    weather:
        class: Wapinet\Bundle\Helper\Weather
        arguments: [@service_container]

    rates:
        class: Wapinet\Bundle\Helper\Rates
        arguments: [@service_container]

    horoscope:
        class: Wapinet\Bundle\Helper\Horoscope
        arguments: [@service_container]

    news:
        class: Wapinet\Bundle\Helper\News
        arguments: [@service_container]

    bash:
        class: Wapinet\Bundle\Helper\Bash
        arguments: [@service_container]

    siza:
        class: Wapinet\Bundle\Helper\Siza
        arguments: [@service_container]

    archive_zip:
        class: Wapinet\Bundle\Helper\Archiver\ArchiveZip
        arguments: [@service_container]

    archive_rar:
        class: Wapinet\Bundle\Helper\Archiver\ArchiveRar
        arguments: [@service_container]

    archive_7z:
        class: Wapinet\Bundle\Helper\Archiver\Archive7z
        arguments: [@service_container]

    wapinet.admin.file:
        class: Wapinet\Bundle\Admin\FileAdmin
        arguments: [null, Wapinet\Bundle\Entity\File, SonataAdminBundle:CRUD]
        calls:
            - [setFileHelper, ["@file"]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Файлы }

