services:
    pagerfanta.view.default:
        class: Wapinet\Bundle\Pagerfanta\View
        public: false
        tags: [{ name: pagerfanta.view, alias: default }]

    wapinet.bbcode.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Bbcode
        tags:
            - {name: twig.extension, alias: wapinet_bbcode}

    wapinet.date.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Date
        tags:
            - {name: twig.extension, alias: wapinet_date}

    wapinet.size.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Size
        tags:
            - {name: twig.extension, alias: wapinet_size}

    wapinet.count.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Count
        tags:
            - {name: twig.extension, alias: wapinet_count}

    wapinet.video.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Video
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_video}

    wapinet.java_app.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\JavaApp
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_java_app}

    wapinet.android_app.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\AndroidApp
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_android_app}

    wapinet.image.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Image
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_image}

    wapinet.archive.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Archive
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_archive}

    wapinet.online.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Online
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: wapinet_online}

    wapinet.breadcrumbs.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Breadcrumbs
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_breadcrumbs}

    wapinet.panel.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Panel
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_panel}

    wapinet.file.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\File
        arguments: [@service_container, @doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: wapinet_file}

    wapinet.guestbook.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Guestbook
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: wapinet_guestbook}

    wapinet.gist.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Gist
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: wapinet_gist}

    base64.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Base64
        tags:
            - {name: twig.extension, alias: base64}

    wapinet.forum.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Forum
        arguments: [@service_container, @doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: wapinet_forum}

    online.listener:
        class: Wapinet\Bundle\Listener\OnlineListener
        arguments: [@service_container, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    error:
        class: Wapinet\Bundle\Helper\Error

    mime:
        class: Wapinet\Bundle\Helper\Mime
        arguments: [@service_container]

    file:
        class: Wapinet\Bundle\Helper\File
        arguments: [@service_container]

    curl:
        class: Wapinet\Bundle\Helper\Curl
        arguments: [@service_container]

    paginate:
        class: Wapinet\Bundle\Helper\Paginate
        arguments: [@service_container]

    getid3:
        class: Wapinet\Bundle\Helper\Getid3

    phpwhois:
        class: Wapinet\Bundle\Helper\Phpwhois

    css_validator:
        class: Wapinet\Bundle\Helper\CssValidator

    html_validator:
        class: Wapinet\Bundle\Helper\HtmlValidator

    php_validator:
        class: Wapinet\Bundle\Helper\PhpValidator
        arguments: [@service_container]

    weather:
        class: Wapinet\Bundle\Helper\Weather
        arguments: [@service_container]

    rates:
        class: Wapinet\Bundle\Helper\Rates
        arguments: [@service_container]

    horoscope:
        class: Wapinet\Bundle\Helper\Horoscope
        arguments: [@service_container]

    mass_media:
        class: Wapinet\Bundle\Helper\MassMedia
        arguments: [@service_container]

    bash:
        class: Wapinet\Bundle\Helper\Bash
        arguments: [@service_container]

    siza:
        class: Wapinet\Bundle\Helper\Siza
        arguments: [@service_container]

    sphinx:
        class: Wapinet\Bundle\Helper\Sphinx
        arguments: [@service_container]
        scope: prototype

    archive_zip:
        class: Wapinet\Bundle\Helper\Archiver\ArchiveZip
        arguments: [@service_container]

    archive_rar:
        class: Wapinet\Bundle\Helper\Archiver\ArchiveRar
        arguments: [@service_container]

    archive_7z:
        class: Wapinet\Bundle\Helper\Archiver\Archive7z
        arguments: [@service_container]

    wapinet.admin.guestbook:
        class: Wapinet\Bundle\Admin\GuestbookAdmin
        arguments: [null, Wapinet\Bundle\Entity\Guestbook, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Гостевая, label: Гостевая }

    wapinet.admin.gist:
        class: Wapinet\Bundle\Admin\GistAdmin
        arguments: [null, Wapinet\Bundle\Entity\Gist, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Блоги, label: Блоги }

    wapinet.admin.file:
        class: Wapinet\Bundle\Admin\FileAdmin
        arguments: [null, Wapinet\Bundle\Entity\File, SonataAdminBundle:CRUD]
        calls:
            - [setFileHelper, ["@file"]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Файлы, label: Файлы }

    wapinet.admin.tag:
        class: Wapinet\Bundle\Admin\TagAdmin
        arguments: [null, Wapinet\Bundle\Entity\Tag, SonataAdminBundle:CRUD]
        calls:
            - [setFileHelper, ["@file"]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Файлы, label: Тэги }

    wapinet.admin.news:
        class: Wapinet\Bundle\Admin\NewsAdmin
        arguments: [~, Wapinet\Bundle\Entity\News, SonataAdminBundle:CRUD]
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Новости, label: Новости}

    wapinet.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\News
        arguments: [@service_container, @doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: news}

