parameters:
    wapinet.controller.paginate.class: Wapinet\Bundle\Controller\PaginateController

services:
    wapinet.paginate.controller:
        class:     "%wapinet.controller.paginate.class%"
        calls:
            - [setContainer, ["@service_container"]]

    wapinet.date.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Date
        tags:
            - {name: twig.extension, alias: wapinet_date}

    wapinet.online.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Online
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: twig.extension, alias: wapinet_online}
