services:
    wapinet.date.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Date
        tags:
            - {name: twig.extension, alias: wapinet_date}

    wapinet.size.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Size
        tags:
            - {name: twig.extension, alias: wapinet_size}

    wapinet.online.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Online
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: twig.extension, alias: wapinet_online}

    wapinet.menu.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Menu
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_menu}

    base64.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Base64
        tags:
            - {name: twig.extension, alias: base64}

    curl:
        class: Wapinet\Bundle\Helper\Curl
        arguments: [@service_container]

    paginate:
        class: Wapinet\Bundle\Helper\Paginate
        arguments: [@service_container]

    getid3:
        class: Wapinet\Bundle\Helper\Getid3
