services:
    wapinet.date.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Date
        tags:
            - {name: twig.extension, alias: wapinet_date}

    wapinet.size.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Size
        tags:
            - {name: twig.extension, alias: wapinet_size}

    wapinet.online.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Online
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: wapinet_online}

    wapinet.breadcrumbs.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Breadcrumbs
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_breadcrumbs}

    wapinet.panel.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Panel
        arguments: [@service_container]
        tags:
            - {name: twig.extension, alias: wapinet_panel}

    base64.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Base64
        tags:
            - {name: twig.extension, alias: base64}

    wapinet.forum.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Forum
        arguments: [@service_container, @doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: wapinet_forum}

    online.listener:
        class: Wapinet\Bundle\Listener\OnlineListener
        arguments: [@service_container, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    curl:
        class: Wapinet\Bundle\Helper\Curl
        arguments: [@service_container]

    paginate:
        class: Wapinet\Bundle\Helper\Paginate
        arguments: [@service_container]

    getid3:
        class: Wapinet\Bundle\Helper\Getid3

    phpwhois:
        class: Wapinet\Bundle\Helper\Phpwhois

    css_validator:
        class: Wapinet\Bundle\Helper\CssValidator

    html_validator:
        class: Wapinet\Bundle\Helper\HtmlValidator

    php_validator:
        class: Wapinet\Bundle\Helper\PhpValidator
        arguments: [@service_container]

    weather:
        class: Wapinet\Bundle\Helper\Weather
        arguments: [@service_container]

    rates:
        class: Wapinet\Bundle\Helper\Rates
        arguments: [@service_container]

    horoscope:
        class: Wapinet\Bundle\Helper\Horoscope
        arguments: [@service_container]

    news:
        class: Wapinet\Bundle\Helper\News
        arguments: [@service_container]

    bash:
        class: Wapinet\Bundle\Helper\Bash
        arguments: [@service_container]

    siza:
        class: Wapinet\Bundle\Helper\Siza
        arguments: [@service_container]

    archive_zip:
        class: Wapinet\Bundle\Helper\Archiver\ArchiveZip
        arguments: [@service_container]

    archive_rar:
        class: Wapinet\Bundle\Helper\Archiver\ArchiveRar
        arguments: [@service_container]

    archive_7z:
        class: Wapinet\Bundle\Helper\Archiver\Archive7z
        arguments: [@service_container]
