parameters:
#    wapinet.example.class: Wapinet\Bundle\Example

services:
    #pagerfanta.view.default:
    #    class: Pagerfanta\View\DefaultView
    #    public: false
    #    tags: [{ name: pagerfanta.view, alias: default }]
