services:
    wapinet.paginate.controller:
        class: Wapinet\Bundle\Controller\PaginateController
        calls:
            - [setContainer, ["@service_container"]]

    wapinet.date.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Date
        tags:
            - {name: twig.extension, alias: wapinet_date}

    wapinet.online.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Online
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: twig.extension, alias: wapinet_online}

    curl_helper:
        class: Wapinet\Bundle\Helper\Curl
        arguments: [@service_container]

    wapinet_menu.builder:
        class: Wapinet\Bundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    wapinet_menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: wapinet_menu.builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
