services:
    wapinet.paginate.controller:
        class: Wapinet\Bundle\Controller\PaginateController
        calls:
            - [setContainer, ["@service_container"]]

    wapinet.date.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Date
        tags:
            - {name: twig.extension, alias: wapinet_date}

    wapinet.online.twig_extension:
        class: Wapinet\Bundle\Twig\Extension\Online
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: twig.extension, alias: wapinet_online}

    curl_helper:
        class: Wapinet\Bundle\Helper\Curl
        arguments: [@service_container]
