Wapinet\Bundle\Entity\User:
    properties:
        avatar:
            - Image:
                minWidth: 13
                maxWidth: 400
                minHeight: 13
                maxHeight: 400