imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru


framework:
    #esi:             ~
    translator:      { fallbacks: ['%locale%', 'en'] }
    secret:          '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: true
    validation:
        enabled: true
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  '%locale%'
    trusted_hosts:   ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        name: wapinet
        cookie_httponly: true
        handler_id:  session.handler.native_file
        save_path:   '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        wapinet_title: '%wapinet_title%'
        wapinet_contact_email: '%wapinet_contact_email%'
        wapinet_git_log: '%wapinet_git_log%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     '%database_path%'
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  '%mailer_transport%'
    host:       '%mailer_host%'
    username:   '%mailer_user%'
    password:   '%mailer_password%'
    encryption: '%mailer_encryption%'
    auth_mode:  '%mailer_auth_mode%'
    port:       '%mailer_port%'
    spool:
        type: memory

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: WapinetBundle\Entity\User
    profile:
        form:
            type: WapinetBundle\Form\Type\User\ProfileType
    from_email:
        address: '%mailer_user%'
        sender_name: '%mailer_user%'

fos_message:
    db_driver: orm
    thread_class: WapinetMessageBundle\Entity\Thread
    message_class: WapinetMessageBundle\Entity\Message
    provider: wapinet_message.provider
    new_thread_form:
        type: WapinetMessageBundle\Form\Type\NewThreadMessageFormType
    reply_form:
        type: WapinetMessageBundle\Form\Type\ReplyMessageFormType

fos_js_routing:
    cache_control:
        public: true
        maxage: 2592000
        expires: '30 days'

vich_uploader:
    db_driver: orm
    mappings:
        file:
            namer: vich_uploader.namer_uniqid
            directory_namer: wapinet.file_uploader.namer_file_directory
            delete_on_update: true # Set to true if the file should be deleted from the filesystem when the file is replaced by an other one
            delete_on_remove: true # determines whether to delete file upon removal of entity
            inject_on_load: true # determines whether to inject a File instance upon load
            uri_prefix: /static/file
            upload_destination: '%kernel.web_dir%/static/file'
    metadata:
            auto_detection: true

gregwar_captcha:
    as_url: true
    reload: true
    length: 5
    width: 200
    height: 46

liip_imagine:
    driver: gd
    filter_sets:
        thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [null, 80], mode: inset }

wapinet:
    ffmpeg_binary: '%wapinet_ffmpeg_path%'
    ffprobe_binary: '%wapinet_ffprobe_path%'
    threads_count: '%wapinet_threads_count%'


easy_admin:
    design:
        assets:
            css:
                - 'bundles/wapinet/css/core.css'
    site_name: '%wapinet_title%'
    entities:
        News:
            label: 'Новости'
            class: WapinetBundle\Entity\News
            list:
                fields:
                    - { property: 'subject', label: 'Заголовок' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'updatedAt', label: 'Дата обновления' }
            form:
                fields:
                    - { property: 'subject', label: 'Заголовок' }
                    - { property: 'body', label: 'Содержание' }
        Users:
            disabled_actions: ['new']
            label: 'Пользователи'
            class: WapinetBundle\Entity\User
            list:
                fields:
                    - { property: 'username', label: 'Логин' }
                    - { property: 'emailCanonical', label: 'Аватар', type: 'image', template: 'avatar.html.twig' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'roles', label: 'Роли' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'lastActivity', label: 'Дата последней активности' }
            form:
                fields:
                    - { property: 'username', label: 'Логин' }
                    - { property: 'enabled', label: 'Активен', type_options: {required: false} }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'roles', label: 'Роли', type: 'choice', type_options: { expanded: true, multiple: true, choices: {ROLE_SUPER_ADMIN: 'Админ', ROLE_ADMIN: 'Модератор', ROLE_USER: 'Пользователь'} } }
                    - { property: 'sex', label: 'Пол', type: 'choice', type_options: {choices: {m: 'Мужской', f: 'Женский'}, required: false} }
                    - { property: 'birthday', label: 'День рождения', type: 'birthday', type_options: {required: false} }
                    - { property: 'timezone', label: 'Временная зона', type: 'timezone', type_options: {required: false} }
                    - { property: 'info', label: 'Дополнительная информация', type: 'textarea', type_options: {required: false} }
        Subscribers:
            disabled_actions: ['new']
            label: 'Подписки'
            class: WapinetBundle\Entity\Subscriber
            list:
                fields:
                    - { property: 'user', label: 'Пользователь' }
                    - { property: 'emailComments', label: 'Комментарии'}
                    - { property: 'emailMessages', label: 'Сообщения' }
                    - { property: 'emailNews', label: 'Новости' }
                    - { property: 'emailFriends', label: 'События друзей' }
            form:
                fields:
                    - { property: 'emailComments', label: 'Комментарии'}
                    - { property: 'emailMessages', label: 'Сообщения' }
                    - { property: 'emailNews', label: 'Новости' }
                    - { property: 'emailFriends', label: 'События друзей' }
        Panel:
            disabled_actions: ['new']
            label: 'Панель'
            class: WapinetBundle\Entity\Panel
            list:
                fields:
                    - { property: 'user', label: 'Пользователь' }
                    - { property: 'forum', label: 'Форум'}
                    - { property: 'guestbook', label: 'Гостевая' }
                    - { property: 'gist', label: 'Блоги' }
                    - { property: 'file', label: 'Файлообменник' }
                    - { property: 'archiver', label: 'Архиватор' }
                    - { property: 'proxy', label: 'Анонимайзер' }
                    - { property: 'downloads', label: 'Развлечения' }
                    - { property: 'utilities', label: 'Утилиты' }
                    - { property: 'programming', label: 'WEB мастерская' }
            form:
                fields:
                    - { property: 'forum', label: 'Форум'}
                    - { property: 'guestbook', label: 'Гостевая' }
                    - { property: 'gist', label: 'Блоги' }
                    - { property: 'file', label: 'Файлообменник' }
                    - { property: 'archiver', label: 'Архиватор' }
                    - { property: 'proxy', label: 'Анонимайзер' }
                    - { property: 'downloads', label: 'Развлечения' }
                    - { property: 'utilities', label: 'Утилиты' }
                    - { property: 'programming', label: 'WEB мастерская' }
        Messages:
            disabled_actions: ['new']
            label: 'Сообщения'
            class: WapinetMessageBundle\Entity\Message
            list:
                fields:
                    - { property: 'sender', label: 'Пользователь' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'body', label: 'Сообщение' }
            form:
                fields:
                    - { property: 'body', label: 'Сообщение', type: 'textarea', type_options: {required: true} }
        Files:
            disabled_actions: ['new']
            label: 'Файлы'
            class: WapinetBundle\Entity\File
            list:
                fields:
                    - { property: 'originalFileName', label: 'Имя файла' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'user', label: 'Пользователь' }
                    - { property: 'mimeType', label: 'MIME тип' }
                    - { property: 'fileSize', label: 'Размер' }
                    - { property: 'description', label: 'Описание' }
                    - { property: 'countViews', label: 'Просмотров' }
                    - { property: 'password', label: 'Пароль', type: 'boolean' }
                    - { property: 'hidden', label: 'Скрыт' }
            form:
                fields:
                    - { property: 'originalFileName', label: 'Имя файла' }
                    - { property: 'mimeType', label: 'MIME тип' }
                    - { property: 'description', label: 'Описание', type: 'textarea' }
                    #- { property: 'meta', label: 'Данные', type_options: { read_only: true, required: false } }
                    - { property: 'countViews', label: 'Просмотров' }
                    - { property: 'hidden', label: 'Скрыт', type_options: {required: false} }
        Tags:
            disabled_actions: ['new']
            label: 'Тэги'
            class: WapinetBundle\Entity\Tag
            list:
                fields:
                    - { property: 'name', label: 'Имя' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'count', label: 'Использовано раз' }
            form:
                fields:
                    - { property: 'name', label: 'Имя' }
                    - { property: 'count', label: 'Использовано раз' }
        Gists:
            disabled_actions: ['new']
            label: 'Блоги'
            class: WapinetBundle\Entity\Gist
            list:
                fields:
                    - { property: 'user', label: 'Пользователь' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'subject', label: 'Тема' }
            form:
                fields:
                    - { property: 'subject', label: 'Тема' }
                    - { property: 'body', label: 'Сообщение' }
        Guestbook:
            disabled_actions: ['new']
            label: 'Гостевая'
            class: WapinetBundle\Entity\Guestbook
            list:
                fields:
                    - { property: 'user', label: 'Пользователь' }
                    - { property: 'createdAt', label: 'Дата создания' }
                    - { property: 'message', label: 'Сообщение' }
            form:
                fields:
                    - { property: 'message', label: 'Сообщение', type: 'textarea' }
