imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: true
    validation:
        enabled: true
        api: 2.5-bc
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: wapinet
        cookie_httponly: true
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        wapinet_title: "%wapinet_title%"
        wapinet_contact_email: "%wapinet_contact_email%"
        wapinet_hg_log: "%wapinet_hg_log%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ "FOSCommentBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }



sonata_admin:
    title:      "%wapinet_title%"
    templates:
        layout:  ::admin.html.twig


sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Wapinet\UserBundle\Entity\User
    profile:
        form:
            type: wapinet_user_profile

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Wapinet\CommentBundle\Entity\Comment
            thread: Wapinet\CommentBundle\Entity\Thread
            vote: Wapinet\CommentBundle\Entity\Vote
    acl: true
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
    acl_roles:
        comment:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN

fos_message:
    db_driver: orm
    thread_class: Wapinet\MessageBundle\Entity\Thread
    message_class: Wapinet\MessageBundle\Entity\Message
    provider: wapinet_message.provider
    new_thread_form:
        type: wapinet_message.new_thread.form.type
    reply_form:
        type: wapinet_message.reply.form.type

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

vich_uploader:
    db_driver: orm
    mappings:
        avatar:
            namer: vich_uploader.namer_uniqid
            directory_namer: wapinet_uploader.avatar_directory_namer
            delete_on_update: true # Set to true if the file should be deleted from the filesystem when the file is replaced by an other one
            delete_on_remove: true # determines whether to delete file upon removal of entity
            inject_on_load: true # determines whether to inject a File instance upon load
            uri_prefix: /static/avatar
            upload_destination: %kernel.web_dir%/static/avatar
        file:
            namer: vich_uploader.namer_uniqid
            directory_namer: wapinet_uploader.file_directory_namer
            delete_on_update: true # Set to true if the file should be deleted from the filesystem when the file is replaced by an other one
            delete_on_remove: true # determines whether to delete file upon removal of entity
            inject_on_load: true # determines whether to inject a File instance upon load
            uri_prefix: /static/file
            upload_destination: %kernel.web_dir%/static/file

gregwar_captcha:
    as_url: true
    reload: true

liip_imagine:
    driver: gd
    filter_sets:
        thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [null, 80], mode: inset }

dubture_f_fmpeg:
    ffmpeg_binary: %wapinet_ffmpeg_path%
    ffprobe_binary: %wapinet_ffprobe_path%

