wapinet:
    resource: "@WapinetBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcbw

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

easy_admin_bundle:
    #resource: "@EasyAdminBundle/Controller/"
    resource: "@WapinetBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
