wapinet:
    resource: "@WapinetBundle/Resources/config/routing.yml"
    prefix:   /

wapinet_user:
    resource: "@WapinetUserBundle/Resources/config/routing.yml"
    prefix:   /

wapinet_message:
    resource: "@WapinetMessageBundle/Resources/config/routing.yml"
    prefix:   /message

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcbw

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

easy_admin_bundle:
    #resource: "@EasyAdminBundle/Controller/"
    resource: "@WapinetBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
