WapinetBundle\Entity\News:
    repositoryClass: WapinetBundle\Entity\NewsRepository
    type:  entity
    table: news
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        subject:
            type: string
            nullable: false
        body:
            type: text
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at

    manyToOne:
        createdBy:
            targetEntity: WapinetUserBundle\Entity\User

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
