WapinetBundle\Entity\Tag:
    repositoryClass: WapinetBundle\Entity\TagRepository
    type:  entity
    table: tag
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    uniqueConstraints:
        name_idx:
            columns: [ name ]
    fields:
        name:
            type: string
            nullable: false
            column: name
        count:
            type: integer
            nullable: false
            column: count
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
