Wapinet\UserBundle\Entity\Subscriber:
    type:  entity
    table: fos_user_subscriber
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        emailComments:
            type: boolean
            nullable: false
            column: email_comments
        emailMessages:
            type: boolean
            nullable: false
            column: email_messages
        emailNews:
            type: boolean
            nullable: false
            column: email_news
        emailFriends:
            type: boolean
            nullable: false
            column: email_friends

    oneToOne:
        user:
            targetEntity: Wapinet\UserBundle\Entity\User
            cascade: ["persist"]
            inversedBy: subscriber
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
