Wapinet\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        subscribeComments:
            type: boolean
            nullable: false
            column: subscribe_comments
        subscribeMessages:
            type: boolean
            nullable: false
            column: subscribe_messages
        avatar:
            type: object
            nullable: true
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        sex:
            type: string
            columnDefinition: ENUM('m', 'f') DEFAULT NULL
            nullable: true
        birthday:
            type: date
            nullable: true

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
