Wapinet\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        avatar:
            type: array
            nullable: true
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        sex:
            type: string
            columnDefinition: ENUM('m', 'f') NOT NULL DEFAULT 'm'
            nullable: false
        birthday:
            type: date
            nullable: true

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
