Wapinet\UserBundle\Entity\User:
    repositoryClass: Wapinet\UserBundle\Entity\UserRepository
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        emailComments:
            type: boolean
            nullable: false
            column: email_comments
        emailMessages:
            type: boolean
            nullable: false
            column: email_messages
        emailNews:
            type: boolean
            nullable: false
            column: email_news
        emailFriends:
            type: boolean
            nullable: false
            column: email_friends
        avatarName:
            type: string
            nullable: true
            column: avatar_name
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        lastActivity:
            type: datetime
            nullable: true
            column: last_activity
        sex:
            type: string
            columnDefinition: ENUM('m', 'f') DEFAULT NULL
            nullable: true
        birthday:
            type: date
            nullable: true
        info:
            type: string
            nullable: true
            length: 5000

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]

    oneToOne:
        panel:
            targetEntity: Wapinet\UserBundle\Entity\Panel
            cascade: ["merge", "remove"]
            joinColumn:
                name: panel_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: true

    oneToMany:
        friends:
            targetEntity: Wapinet\UserBundle\Entity\Friend
            mappedBy: user
            cascade: ["persist", "remove"]
            orphanRemoval: true
            orderBy:
                id: DESC
        friended:
            targetEntity: Wapinet\UserBundle\Entity\Friend
            mappedBy: friend
            orderBy:
                id: DESC
