wapinet_news:
    pattern:  /{page}
    defaults: { _controller: WapinetNewsBundle:News:index, page: 1 }
    requirements:
        id: \d+

wapinet_news_show:
    pattern:  /show/{id}
    defaults: { _controller: WapinetNewsBundle:News:show }
    requirements:
        id: \d+