services:
    wapinet_news.admin.news:
        class: Wapinet\NewsBundle\Admin\NewsAdmin
        arguments: [~, Wapinet\NewsBundle\Entity\News, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Новости, label: Новости}

    wapinet_news.twig_extension:
        class: Wapinet\NewsBundle\Twig\Extension\NewsExtension
        arguments: [@service_container, @doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: wapinet_news}
