services:
    wapinet_message.provider:
        class: WapinetMessageBundle\Provider\Provider
        public: false
        calls:
            - [setContainer, ["@service_container"]]
        arguments: ["@fos_message.thread_manager", "@fos_message.message_manager", "@fos_message.thread_reader", "@fos_message.authorizer", "@fos_message.participant_provider"]

    #fix for symfony 3.4 / 4
    FOS\MessageBundle\ModelManager\MessageManagerInterface: "@fos_message.message_manager.default"
