services:
    wapinet_user.profile.form.type:
        class: WapinetUserBundle\Form\Type\ProfileType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: wapinet_user_profile }

    wapinet_user.event.message:
        class: WapinetUserBundle\EventListener\EventMessage
        arguments: ["@fos_message.message_manager", "@doctrine.orm.entity_manager", "@router"]
        tags:
            - { name: kernel.event_subscriber }

    wapinet_user.listener.last_activity:
            class: WapinetUserBundle\EventListener\ListenerLastActivity
            arguments: ["@service_container", "@doctrine.orm.entity_manager"]
            tags:
                - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

#    wapinet_user.friend.twig_extension:
#        class: WapinetUserBundle\Twig\Extension\Friend
#        arguments: ["@doctrine.orm.entity_manager"]
#        tags:
#            - {name: twig.extension, alias: wapinet_user_friend}

#    wapinet_user.avatar.twig_extension:
#        class: WapinetUserBundle\Twig\Extension\Avatar
#        tags:
#            - {name: twig.extension, alias: wapinet_user_avatar}

    wapinet_user.event.friends:
        class: WapinetUserBundle\EventListener\EventFriends
        arguments: ["@doctrine.orm.entity_manager", "@router"]
        tags:
            - { name: kernel.event_subscriber }
