wapinet_message_inbox:
    path:  /inbox
    defaults: { _controller: WapinetMessageBundle:Message:inbox }

wapinet_message_sent:
    path:  /sent
    defaults: { _controller: WapinetMessageBundle:Message:sent }

wapinet_message_deleted:
    path:  /deleted
    defaults: { _controller: WapinetMessageBundle:Message:deleted }

wapinet_message_thread_view:
    path: /{threadId}
    defaults: {_controller: WapinetMessageBundle:Message:thread }
    requirements:
        threadId: \d+

wapinet_message_thread_new:
    path: /new/{recipient}
    defaults: {_controller: WapinetMessageBundle:Message:newThread, recipient: null }

wapinet_message_thread_delete:
    path: /{threadId}/delete
    methods: [POST, DELETE]
    defaults: {_controller: WapinetMessageBundle:Message:delete }

wapinet_message_thread_undelete:
    path: /{threadId}/undelete
    methods: [POST]
    defaults: {_controller: WapinetMessageBundle:Message:undelete }

