wapinet_message_inbox:
    pattern:  /inbox
    defaults: { _controller: WapinetMessageBundle:Message:inbox }

wapinet_message_sent:
    pattern:  /sent
    defaults: { _controller: WapinetMessageBundle:Message:sent }

wapinet_message_deleted:
    pattern:  /deleted
    defaults: { _controller: WapinetMessageBundle:Message:deleted }

wapinet_message_thread_view:
    pattern: /{threadId}
    defaults: {_controller: WapinetMessageBundle:Message:thread }
    requirements:
        threadId: \d+

wapinet_message_thread_new:
    pattern: /new/{recipient}
    defaults: {_controller: WapinetMessageBundle:Message:newThread, recipient: null }

