App\Entity\File:
    properties:
        file:
            - File: ~
        description:
            - Length:
                max: 5000
            - NotBlank: ~
App\Entity\Gist:
    properties:
        subject:
            - Length:
                max: 5000
            - NotBlank: ~
        body:
            - Length:
                max: 4294967295
            - NotBlank: ~
App\Entity\Guestbook:
    properties:
        message:
            - Length:
                max: 5000
            - NotBlank: ~
