archiver_index:
    pattern: /
    defaults: { _controller: WapinetBundle:Archiver:index }

archiver_create:
    pattern: /create
    defaults: { _controller: WapinetBundle:Archiver:create }

