archiver_index:
    pattern: /
    defaults: { _controller: WapinetBundle:Archiver:index }

archiver_create:
    pattern: /create
    defaults: { _controller: WapinetBundle:Archiver:create }

archiver_edit:
    pattern: /edit/{archive}
    defaults: { _controller: WapinetBundle:Archiver:edit }
    requirements:
        archive: "archive[a-z0-9]+"

archiver_download:
    pattern: /download/{archive}.zip
    defaults: { _controller: WapinetBundle:Archiver:download }
    requirements:
        archive: "archive[a-z0-9]+"

