audio_tags_index:
    pattern: /
    defaults: { _controller: WapinetBundle:AudioTags:index }

audio_tags_edit:
    pattern: /edit/{fileName}/{originalFileName}
    defaults: { _controller: WapinetBundle:AudioTags:edit }

audio_tags_download:
    pattern: /download/{fileName}/{originalFileName}
    defaults: { _controller: WapinetBundle:AudioTags:download }
