file_index:
    pattern: /
    defaults: { _controller: WapinetBundle:File:index }

file_information:
    pattern: /information
    defaults: { _controller: WapinetBundle:File:information }

file_statistic:
    pattern: /statistic
    defaults: { _controller: WapinetBundle:File:statistic }

file_upload:
    pattern: /upload
    defaults: { _controller: WapinetBundle:File:upload }

file_edit:
    pattern: /edit/{id}
    defaults: { _controller: WapinetBundle:File:edit }
    requirements:
        id: \d+

file_delete:
    pattern: /delete/{id}
    defaults: { _controller: WapinetBundle:File:delete }
    methods: [POST]
    requirements:
        id: \d+

file_search:
    pattern: /search/{key}
    defaults: { _controller: WapinetBundle:File:search, key: null }
    requirements:
        key: "[a-zA-Z0-9]+"

file_tags:
    pattern: /tags
    defaults: { _controller: WapinetBundle:File:tags }

file_tag:
    pattern: /tags/{tagName}
    defaults: { _controller: WapinetBundle:File:tag }
    requirements:
        tagName: ".+"

file_user:
    pattern: /users/{username}
    defaults: { _controller: WapinetBundle:File:user }
    requirements:
        username: ".+"

file_categories:
    pattern: /categories
    defaults: { _controller: WapinetBundle:File:categories }

file_list:
    pattern: /list/{date}/{category}
    defaults: { _controller: WapinetBundle:File:list, date: all, category: null }
    requirements:
        date: (all|today|yesterday)
        category: (video|audio|image|text|office|archive|android|java)

file_view:
    pattern: /{id}
    defaults: { _controller: WapinetBundle:File:view }
    requirements:
        id: \d+

file_archive_download_file:
    pattern: /{id}/download/{name}
    defaults: { _controller: WapinetBundle:File:archiveDownloadFile }
    requirements:
        id: \d+


