file_index:
    pattern: /
    defaults: { _controller: WapinetBundle:File:index }

file_information:
    pattern: /information
    defaults: { _controller: WapinetBundle:File:information }

file_statistic:
    pattern: /statistic
    defaults: { _controller: WapinetBundle:File:statistic }

file_upload:
    pattern: /upload
    defaults: { _controller: WapinetBundle:File:upload }

file_search:
    pattern: /search/{page}/{key}
    defaults: { _controller: WapinetBundle:File:search, page: 1, key: null }
    requirements:
        page: \d+
        key: "[a-zA-Z0-9]+"

file_categories:
    pattern: /categories
    defaults: { _controller: WapinetBundle:File:categories }

file_list:
    pattern: /list/{page}/{date}/{category}
    defaults: { _controller: WapinetBundle:File:list, page: 1, date: all, category: null }
    requirements:
        page: \d+
        date: (all|today|yesterday)
        category: (video|audio|image|text|office|archive|android|java)

file_view:
    pattern: /{id}
    defaults: { _controller: WapinetBundle:File:view }
    requirements:
        id: \d+


