file_index:
    path: /
    defaults: { _controller: WapinetBundle:File:index }

file_information:
    path: /information
    defaults: { _controller: WapinetBundle:File:information }

file_statistic:
    path: /statistic
    defaults: { _controller: WapinetBundle:File:statistic }

file_upload:
    path: /upload
    defaults: { _controller: WapinetBundle:File:upload }

file_edit:
    path: /edit/{id}
    defaults: { _controller: WapinetBundle:File:edit }
    requirements:
        id: \d+

file_accept:
    path: /accept/{id}
    defaults: { _controller: WapinetBundle:File:accept }
    requirements:
        id: \d+

file_delete:
    path: /delete/{id}
    defaults: { _controller: WapinetBundle:File:delete }
    methods: [POST]
    requirements:
        id: \d+

file_search:
    path: /search/{key}
    defaults: { _controller: WapinetBundle:File:search, key: null }
    requirements:
        key: "[a-zA-Z0-9]+"

file_hidden:
    path: /hidden
    defaults: { _controller: WapinetBundle:File:hidden }

file_tags:
    path: /tags
    defaults: { _controller: WapinetBundle:File:tags }

file_tag:
    path: /tags/{tagName}
    defaults: { _controller: WapinetBundle:File:tag }
    requirements:
        tagName: ".+"

file_tags_search:
    path: /tags_search
    defaults: { _controller: WapinetBundle:File:tagsSearch, _format: json }

file_user:
    path: /users/{username}
    defaults: { _controller: WapinetBundle:File:user }
    requirements:
        username: ".+"

file_categories:
    path: /categories
    defaults: { _controller: WapinetBundle:File:categories }

file_list:
    path: /list/{date}/{category}
    defaults: { _controller: WapinetBundle:File:list, date: all, category: null }
    requirements:
        date: (all|today|yesterday)
        category: (video|audio|image|text|office|archive|android|java)

file_view:
    path: /{id}
    defaults: { _controller: WapinetBundle:File:view }
    requirements:
        id: \d+

file_archive_download_file:
    path: /{id}/download/{name}
    defaults: { _controller: WapinetBundle:File:archiveDownloadFile }
    requirements:
        id: \d+

file_swiper:
    path: /swiper/{id}
    defaults: { _controller: WapinetBundle:File:swiper }
    requirements:
        id: \d+

