gist_index:
    path: /
    defaults: { _controller: WapinetBundle:Gist:index }
    options:
        expose: true

gist_user:
    path: /users/{username}
    defaults: { _controller: WapinetBundle:Gist:user }
    requirements:
        username: ".+"

gist_view:
    path: /view/{id}
    defaults: { _controller: WapinetBundle:Gist:view }
    requirements:
        id: \d+

gist_delete:
    path: /delete/{id}
    defaults: { _controller: WapinetBundle:Gist:delete }
    methods: [POST]
    requirements:
        id: \d+
    options:
        expose: true

gist_add:
    path: /add
    defaults: { _controller: WapinetBundle:Gist:add }
    methods: [POST]

gist_edit:
    path: /edit/{id}
    defaults: { _controller: WapinetBundle:Gist:edit }
    requirements:
        id: \d+

gist_search:
    path: /search/{key}
    defaults: { _controller: WapinetBundle:Gist:search, key: null }
    requirements:
        key: "[a-zA-Z0-9]+"


