guestbook_index:
    path: /
    defaults: { _controller: WapinetBundle:Guestbook:index }

guestbook_add:
    path: /add
    defaults: { _controller: WapinetBundle:Guestbook:add }
    methods: [POST]


