guestbook_index:
    path: /
    defaults: { _controller: WapinetBundle:Guestbook:index }
    methods:  [GET, HEAD]

guestbook_add:
    path: /
    defaults: { _controller: WapinetBundle:Guestbook:add }
    methods: [POST]
