horoscope_index:
    path: /
    defaults: { _controller: WapinetBundle:Horoscope:index }

horoscope_show:
    path: /{zodiac}
    defaults: { _controller: WapinetBundle:Horoscope:show }
    requirements:
        zodiac: (aquarius|aries|cancer|capricorn|gemini|leo|libra|pisces|sagittarius|scorpio|taurus|virgo)

horoscope_day:
    path: /day
    defaults: { _controller: WapinetBundle:Horoscope:day }

