icq_index:
    path: /
    defaults: { _controller: WapinetBundle:Icq:index }

icq_about:
    path: /about
    defaults: { _controller: WapinetBundle:Icq:about }

icq_invise:
    path: /invise
    defaults: { _controller: WapinetBundle:Icq:invise }

icq_secure:
    path: /secure
    defaults: { _controller: WapinetBundle:Icq:secure }

icq_servers:
    path: /servers
    defaults: { _controller: WapinetBundle:Icq:servers }

icq_clients:
    path: /clients
    defaults: { _controller: WapinetBundle:Icq:clients }

icq_services:
    path: /services
    defaults: { _controller: WapinetBundle:Icq:services }

icq_disconnect:
    path: /disconnect
    defaults: { _controller: WapinetBundle:Icq:disconnect }

icq_errors:
    path: /errors
    defaults: { _controller: WapinetBundle:Icq:errors }

icq_search:
    path: /search
    defaults: { _controller: WapinetBundle:Icq:search }
