news_index:
    pattern: /
    defaults: { _controller: WapinetBundle:News:index }

news_rt:
    pattern: /rt
    defaults: { _controller: WapinetBundle:News:rt }

news_inotv:
    pattern: /inotv
    defaults: { _controller: WapinetBundle:News:inotv }

