weather_country:
    path: /
    defaults: { _controller: WapinetBundle:Weather:country }

weather_country_search:
    path: /country_search
    defaults: { _controller: WapinetBundle:Weather:countrySearch }

weather_city:
    path: /{country}
    defaults: { _controller: WapinetBundle:Weather:city, country: null }
    requirements:
        country: \d+

weather_city_search:
    path: /{country}/city_search
    defaults: { _controller: WapinetBundle:Weather:citySearch }
    requirements:
        country: \d+

weather_show:
    path: /{country}/{city}
    defaults: { _controller: WapinetBundle:Weather:show, city: null }
    requirements:
        country: \d+
        city: \d+

