gist_index:
    path: /
    defaults: { _controller: App\Controller\GistController:indexAction }
    methods:  [GET, HEAD]
    options:
        expose: true

gist_user:
    path: /users/{username}
    defaults: { _controller: App\Controller\GistController:userAction }
    requirements:
        username: ".+"

gist_view:
    path: /view/{id}
    defaults: { _controller: App\Controller\GistController:viewAction }
    requirements:
        id: \d+

gist_delete:
    path: /delete/{id}
    defaults: { _controller: App\Controller\GistController:deleteAction }
    methods: [POST]
    requirements:
        id: \d+
    options:
        expose: true

gist_add:
    path: /
    defaults: { _controller: App\Controller\GistController:addAction }
    methods: [POST]

gist_edit:
    path: /edit/{id}
    defaults: { _controller: App\Controller\GistController:editAction }
    requirements:
        id: \d+

gist_search:
    path: /search/{key}
    defaults: { _controller: App\Controller\GistController:searchAction, key: null }
    requirements:
        key: "[a-zA-Z0-9]+"


