services:
    wapinet_uploader.type.file_url:
        class: Wapinet\UploaderBundle\Form\Type\FileUrlType
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: file_url }

    wapinet_uploader.user_avatar_directory_namer:
        class: Wapinet\UploaderBundle\Naming\UserAvatarDirectoryNamer
        tags:
            - { name: user_avatar_directory_namer }

    wapinet_uploader.file_directory_namer:
        class: Wapinet\UploaderBundle\Naming\FileDirectoryNamer
        tags:
            - { name: file_directory_namer }

    wapinet_uploader.delete_file:
        class: Wapinet\UploaderBundle\Helper\DeleteFile
        arguments: [@request_stack, @vich_uploader.property_mapping_factory]
