services:
    wapinet_uploader.type.file_url:
        class: Wapinet\UploaderBundle\Form\Type\FileUrlType
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: file_url }

    wapinet_uploader.directory_namer:
        class: Wapinet\UploaderBundle\Naming\DirectoryNamer
        tags:
            - { name: directory_namer }

    wapinet_uploader.listener.uploader:
        class: Wapinet\UploaderBundle\EventListener\UploaderListener
        public: false
        arguments: [@vich_uploader.adapter, @vich_uploader.annotation_driver, @vich_uploader.storage, @vich_uploader.file_injector]
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
