audio_tags_index:
    path: /
    defaults: { _controller: WapinetBundle:AudioTags:index }

audio_tags_edit:
    path: /edit/{fileName}/{originalFileName}
    defaults: { _controller: WapinetBundle:AudioTags:edit }

audio_tags_download:
    path: /download/{fileName}/{originalFileName}
    defaults: { _controller: WapinetBundle:AudioTags:download }
