mass_media_index:
    path: /
    defaults: { _controller: WapinetBundle:MassMedia:index }

mass_media_rt:
    path: /rt
    defaults: { _controller: WapinetBundle:MassMedia:rt }

mass_media_inotv:
    path: /inotv
    defaults: { _controller: WapinetBundle:MassMedia:inotv }

