rates_index:
    path: /
    defaults: { _controller: WapinetBundle:Rates:index }

rates_show:
    path: /{country}
    defaults: { _controller: WapinetBundle:Rates:show }
    requirements:
        country: (ru|by|ua|kz)

