siza_index:
    path: /
    defaults: { _controller: WapinetBundle:Siza:index }

siza_search:
    path: /search
    defaults: { _controller: WapinetBundle:Siza:search }


siza_search_list:
    path: /search/{searchId}
    defaults: { _controller: WapinetBundle:Siza:searchList }
    requirements:
        searchId: \d+
