wapinet_user_profile:
    pattern:  /profile/user/{username}
    defaults: { _controller: WapinetUserBundle:Profile:showUser, username: null }
    requirements:
        _method: GET

wapinet_user_panel_edit:
    pattern:  /panel/edit
    defaults: { _controller: WapinetUserBundle:Panel:edit }

wapinet_user_comments:
    pattern:  /comments/{username}
    defaults: { _controller: WapinetUserBundle:Comments:index }

wapinet_users:
    pattern:  /users/{key}
    defaults: { _controller: WapinetUserBundle:Users:index, key: null }
    requirements:
        key: "[a-zA-Z0-9]+"

wapinet_user_friends:
    pattern:  /friends/{username}
    defaults: { _controller: WapinetUserBundle:Friends:index }

wapinet_user_friends_add:
    pattern:  /friends/add/{username}
    defaults: { _controller: WapinetUserBundle:Friends:add }

wapinet_user_friends_delete:
    pattern:  /friends/delete/{username}
    defaults: { _controller: WapinetUserBundle:Friends:delete }

