wapinet_user_profile:
    path:  /profile/user/{username}
    defaults: { _controller: WapinetUserBundle:Profile:showUser, username: null }
    methods: [GET]

wapinet_user_panel_edit:
    path:  /panel/edit
    defaults: { _controller: WapinetUserBundle:Panel:edit }

wapinet_user_subscriber_edit:
    path:  /subscriber/edit
    defaults: { _controller: WapinetUserBundle:Subscriber:edit }

wapinet_user_events:
    path:  /events
    defaults: { _controller: WapinetUserBundle:Events:index }

wapinet_user_comments:
    path:  /comments/{username}
    defaults: { _controller: WapinetUserBundle:Comments:index }

wapinet_users:
    path:  /users/{key}
    defaults: { _controller: WapinetUserBundle:Users:index, key: null }
    requirements:
        key: "[a-zA-Z0-9]+"

wapinet_user_friends:
    path:  /friends/{username}
    defaults: { _controller: WapinetUserBundle:Friends:index }

wapinet_user_friends_add:
    path:  /friends/add/{username}
    defaults: { _controller: WapinetUserBundle:Friends:add }

wapinet_user_friends_delete:
    path:  /friends/delete/{username}
    defaults: { _controller: WapinetUserBundle:Friends:delete }

