fos_user_profile_show:
    pattern:  /{id}
    defaults: { _controller: WapinetUserBundle:Profile:show, id: null }
    requirements:
        id: \d+
        _method: GET

fos_user_profile_edit:
    pattern: /edit
    defaults: { _controller: WapinetUserBundle:Profile:edit }
