fos_user_profile_show:
    pattern:  /{username}
    defaults: { _controller: WapinetUserBundle:Profile:show, username: null }
    requirements:
        _method: GET

fos_user_profile_edit:
    pattern: /edit
    defaults: { _controller: WapinetUserBundle:Profile:edit }
