wapinet_user_profile:
    pattern:  /profile/user/{username}
    defaults: { _controller: WapinetUserBundle:Profile:showUser, username: null }
    requirements:
        _method: GET

wapinet_user_panel_edit:
    pattern:  /panel/edit
    defaults: { _controller: WapinetUserBundle:Panel:edit }

wapinet_user_comments:
    pattern:  /comments/{username}
    defaults: { _controller: WapinetUserBundle:Comments:index }

