fos_user_profile_show:
    pattern:  /profile
    defaults: { _controller: WapinetUserBundle:Profile:show }
    requirements:
        _method: GET

fos_user_profile_edit:
    pattern: /profile/edit
    defaults: { _controller: WapinetUserBundle:Profile:edit }
