services:
    wapinet_user.profile.form.type:
        class: Wapinet\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%, @service_container]
        tags:
            - { name: form.type, alias: wapinet_user_profile }

    wapinet_user.admin.user:
        class: Wapinet\UserBundle\Admin\UserAdmin
        arguments: [null, Wapinet\UserBundle\Entity\User, SonataAdminBundle:CRUD]
        calls:
            - [setUserManager, ["@fos_user.user_manager"]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Пользователи }

    wapinet_user.admin.panel:
        class: Wapinet\UserBundle\Admin\PanelAdmin
        arguments: [null, Wapinet\UserBundle\Entity\Panel, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Меню }

    wapinet_user.subscriber.message:
        class: Wapinet\UserBundle\EventListener\SubscriberMessage
        arguments: [@fos_message.message_manager, @doctrine.orm.entity_manager, @router]
        tags:
            - { name: kernel.event_subscriber }

    wapinet_user.subscriber.comment:
        class: Wapinet\UserBundle\EventListener\SubscriberComment
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_subscriber }

    wapinet_user.listener.last_activity:
            class: Wapinet\UserBundle\EventListener\ListenerLastActivity
            arguments: [@service_container, @doctrine.orm.entity_manager]
            tags:
                - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
