services:
    wapinet_user.profile.form.type:
        class: Wapinet\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: wapinet_user_profile }

    wapinet_user.admin.user:
        class: Wapinet\UserBundle\Admin\UserAdmin
        calls:
            - [setUserManager, ["@fos_user.user_manager"]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Пользователи, label: Пользователи }
        arguments: [null, Wapinet\UserBundle\Entity\User, SonataAdminBundle:CRUD]
