Wapinet\UserBundle\Entity\User:
    properties:
        avatar:
            - Image:
                maxSize: 200k
                minWidth: 13
                maxWidth: 500
                minHeight: 13
                maxHeight: 500