Wapinet\UserBundle\Entity\User:
    properties:
        avatar:
            - Image:
                minWidth: 13
                maxWidth: 500
                minHeight: 13
                maxHeight: 500
                maxSize: 100k
                mimeTypes: [image/png, image/jpeg, image/gif]