WapinetUserBundle\Entity\Event:
    repositoryClass: WapinetUserBundle\Entity\EventRepository
    type:  entity
    table: event
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        subject:
            type: string
            nullable: false
        variables:
            type: array
            nullable: true
        template:
            type: string
        needEmail:
            type: boolean
            nullable: false
            column: need_email

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]

    manyToOne:
        user:
            type: integer
            targetEntity: WapinetUserBundle\Entity\User
            joinColumns:
                user_id:
                    onDelete: CASCADE
                    onUpdate: CASCADE # не ставится автоматически. проставить вручную.
                    nullable: false
