App\Entity\FileTags:
    type:  entity
    table: file_tags
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    lifecycleCallbacks:
        prePersist: [ setPrePersistValue ]
        preUpdate: [ setPreUpdateValue ]
        preRemove: [ setPreRemoveValue ]
    manyToOne:
        file:
            targetEntity: App\Entity\File
            cascade: ["persist"]
            inversedBy: fileTags
            joinColumn:
                name: file_id
                referencedColumnName: id
                nullable: false
        tag:
            targetEntity: App\Entity\Tag
            cascade: ["persist"]
            joinColumn:
                name: tag_id
                referencedColumnName: id
                nullable: false