App\Entity\Friend:
    repositoryClass: App\Repository\FriendRepository
    type:  entity
    table: user_friend
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]

    manyToOne:
        user:
            targetEntity: App\Entity\User
            inversedBy: friends
        friend:
            targetEntity: App\Entity\User
            inversedBy: friended
