App\Entity\Subscriber:
    type:  entity
    table: user_subscriber
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        emailNews:
            type: boolean
            nullable: false
            column: email_news
        emailFriends:
            type: boolean
            nullable: false
            column: email_friends

    oneToOne:
        user:
            targetEntity: App\Entity\User
            cascade: ["persist"]
            inversedBy: subscriber
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
