App\Entity\User:
    repositoryClass: App\Repository\UserRepository
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        username:
            unique: true
            type: string
            length: 180
            nullable: false
        email:
            unique: true
            type: string
            length: 180
            nullable: false
        salt:
            type: string
            length: 255
            nullable: true
        password:
            type: string
            length: 255
            nullable: false
        roles:
            type: array
        lastActivity:
            type: datetime
            nullable: true
            column: last_activity
        sex:
            type: string
            columnDefinition: ENUM('m', 'f') DEFAULT NULL
            nullable: true
        birthday:
            type: date
            nullable: true
        info:
            type: string
            nullable: true
            length: 5000
        timezone:
            type: string
            nullable: true
        country:
            type: string
            nullable: true
        vk:
            type: string
            nullable: true

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]

    oneToOne:
        panel:
            targetEntity: App\Entity\Panel
            cascade: ["persist", "remove"]
            mappedBy: user
            joinColumn:
                name: panel_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: true
        subscriber:
            targetEntity: App\Entity\Subscriber
            mappedBy: user
            cascade: ["persist", "remove"]
            joinColumn:
                name: subscriber_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: true

    oneToMany:
        friends:
            targetEntity: App\Entity\Friend
            mappedBy: user
            cascade: ["persist", "remove"]
            orphanRemoval: true
            orderBy:
                id: DESC
        friended:
            targetEntity: App\Entity\Friend
            mappedBy: friend
            orderBy:
                id: DESC
